---
ansible_user: cisco
ansible_password: cisco
ansible_network_os: ios
ansible_connection: network_cli
ansible_become: yes
ansible_become_method: enable
ansible_become_password: cisco
ansible_python_interpreter: '~/venv/netauto_learning/bin/python'